<script lang="ts">
  import { onMount } from 'svelte';
  type Department = { id: string; code: string; name: string; member_count: number };
  let departments: Department[] = $state([]);
  let code = $state(''); let name = $state(''); let message = $state(''); let error = $state(''); let loading = $state(true);
  onMount(async () => { try { const response = await fetch('/api/departments'); const data = await response.json(); departments = data.departments ?? []; error = data.error ?? ''; } catch { error = 'Unable to load departments.'; } finally { loading = false; } });
  async function save() { message = ''; error = ''; const response = await fetch('/api/departments', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: code.toLowerCase(), code, name }) }); const data = await response.json(); if (response.ok) { message = 'Department saved.'; code = ''; name = ''; const refreshed = await fetch('/api/departments'); departments = (await refreshed.json()).departments ?? []; } else error = data.error ?? 'Unable to save department.'; }
</script>
<svelte:head><title>Departments · Faculty Reporting System</title></svelte:head>
<main class="shell app-shell"><div class="breadcrumb">Administration <span>/</span> Departments</div><div class="page-heading"><div><div class="eyebrow">Administration</div><h1>Departments</h1><p>Maintain institution departments and reporting membership.</p></div></div>{#if message}<div class="message">{message}</div>{/if}{#if error}<div class="error">{error}</div>{/if}{#if loading}<div class="loading-panel"><span class="spinner"></span><span>Loading departments…</span></div>{:else}<section class="department-layout"><div class="directory"><h2>Department directory</h2>{#if !departments.length}<div class="empty-state">No departments configured.</div>{:else}{#each departments as department}<div class="department-row"><div><strong>{department.code}</strong><span>{department.name}</span></div><small>{department.member_count} member{department.member_count === 1 ? '' : 's'}</small></div>{/each}{/if}</div><form class="create-panel" onsubmit={(event) => { event.preventDefault(); save(); }}><h2>Add or update department</h2><label>Department code<input bind:value={code} required placeholder="CSE" /></label><label>Department name<input bind:value={name} required placeholder="Computer Science and Engineering" /></label><button class="approve" type="submit">Save department</button></form></section>{/if}</main>
<style>.breadcrumb{font-size:.73rem;color:#71818a;margin-bottom:8px}.breadcrumb span{padding:0 8px;color:#b2bdc1}.loading-panel{display:flex;align-items:center;gap:12px;padding:24px;color:#71818a;font-size:.88rem}.spinner{width:18px;height:18px;border:2px solid #dbe3e7;border-top-color:#087f73;border-radius:50%;animation:spin .6s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.department-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.directory,.create-panel{background:#fdfcf9;border:1px solid #dbe3e7;border-radius:7px;padding:20px}.directory h2,.create-panel h2{font-size:1rem;margin:0 0 12px}.department-row{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e6ecee;padding:14px 0}.department-row strong,.department-row span{display:block}.department-row strong{color:#087f73;font-size:.8rem}.department-row span{color:#1b2b36;font-size:.78rem;margin-top:4px}.department-row small{color:#87969c;font-size:.7rem}.empty-state{padding:18px 0;color:#87969c;font-size:.8rem}.create-panel{display:grid;align-content:start;gap:15px}.create-panel label{font-size:.75rem;color:#40535f;font-weight:750}.create-panel input{width:100%;display:block;margin-top:6px;padding:10px;border:1px solid #c8d5da;border-radius:5px;font:inherit}.approve{border:0;background:#172a3a;color:#fdfcf9;border-radius:5px;padding:11px 14px;font:inherit;font-size:.78rem;font-weight:800;cursor:pointer}.message,.error{padding:11px 14px;border-radius:5px;margin-bottom:18px;font-size:.78rem}.message{background:#e4f3ef;color:#167166}.error{background:#f9e9e7;color:#8f413b}@media(max-width:700px){.department-layout{grid-template-columns:1fr}}</style>